### ISSUE TITLE
Missing KAT for failed Decaps causes coverage gap

### ISSUE THREAD

**Issue by rod-chapman** [post-quantum-cryptography/KAT#3]
Could we add a KAT that covers the case there the validation check in ML-KEM.Decaps fails? That's lines 9-11 of Algorithm 17 in the spec.

Lack of this KAT causes a structural coverage gap in my test results because line 10 (K_Tick := K_Hat) is never executed with the current set of KATs.

**Comment by kriskwiatkowski** [comment]
On it.

**Comment by rod-chapman** [comment]
Kris - on further investigation (i.e. I asked Peter S) reveals that the "if" statement is probably a mistake. Algorithm 17 is supposed to exhibit cryptographic constant time, so it really should be specified to use a constant-time conditional swap in order to retain the "implicit rejection" property.  I will add a note to that affect in our comments for NIST.

Nevertheless, it will still be good to have a KAT that covers the "reject" case.

**Comment by kriskwiatkowski** [comment]
Yes, that's what I thought. It would be good to have something that covers that case (indeed, this check must be constant time in order to avoid attacks like the one in the https://eprint.iacr.org/2020/743)

The thing is, I need to change structure of the KATs vectors. Basically, we need a way to says that "for this KAT, the decapsulation must NOT generate same shared secret as encapsulation). So, instead of having ``ss``, we should either have two of them (``ss_encaps`` and ``ss_decaps``) or to have just a flag that says that decapsulation generates different ``ss``.

**Comment by kriskwiatkowski** [comment]
@rod-chapman I've just added those tests. Namely I've added two fields to each test vector  (ct_n and ss_n). The 'ct_n' is a random stream of bytes, when one tries to use it to in decapsulation, it should get `ss_n` value (aka KBar).

**Comment by rod-chapman** [comment]
Noted - I will try to reproduce and confirm.

**Comment by rod-chapman** [comment]
OK... my code updated with reproduces results exactly, so looking good.

**Comment by kriskwiatkowski** [comment]
Alright, thanks for checking.
Closing this issue then.
